# Generated by Django 4.1.3 on 2022-12-09 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredientMix", to="recipes.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientmix",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_mix",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientmix",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredientset",
                to="recipes.recipe",
            ),
        ),
    ]
