# Generated by Django 4.1.3 on 2022-12-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recipes.category",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientmix",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_mix_set",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientmix",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_mix_set",
                to="recipes.recipe",
            ),
        ),
    ]
